### ISSUE TITLE
NFVO package not longer distributed with Makefile

### ISSUE THREAD

**Issue by rgaglian** [NSO-developer/tme-demo#10]
As you cannot compile the external dependencies any longer, we need to change the demo Makefile.

EXTERNAL_DEPS = resource-manager esc openstack-cos-gen-4.2 \
	              etsi-sol003-gen-1.13 cisco-etsi-nfv

Should be
EXTERNAL_DEPS = resource-manager

**Comment by maddn** [comment]
This has been fixed in commit c25aabbcf9ccd273913ec5f9ef116f4526554ef0

The latest version no longer compiles the dependent packages (see the Makefile comments for details).
