### ISSUE TITLE
The build process of this demo will fail due to cisco-etsi-nfvo

### ISSUE THREAD

**Issue by dmontagner** [NSO-developer/tme-demo#3]
The Makefile of this project will try to compile the dependency package `cisco-etsi-nfvo`.

Since the source code of this package is not shipped together like the other packages, the `make all` will fail when it enters `packages/cisco-etsi-nfvo/src` and looks for the `.mk` file.

**Comment by maddn** [comment]
Hi. Unfortunately there's no easy work around for this. One of the puposes of this demo is to show NFVO features, so ```cisco-etsi-nfvo``` is a required dependency.

If you are part of the NSO development team and have access to the internal git repos, the package will be cloned automatically, but for everyone else, the package must be manually copied to the packages directory before compiling. The process is described in the ```README``` in the Dependencies section.

**Comment by dmontagner** [comment]
Hi @maddn 

that's what I did. I manually copied the cisco-etsi-nfvo there.

The main issue is because I am building the demo, the Makefile for the dependencies will always look for the `.mk` file for cisco-etsi-nfvo. Hence, it breaks the build process. 

The Makefile should be updated with a toggle to bypass the `.mk` file if the dependency is manually copied there.
