### ISSUE TITLE
Dependencie missing for xsltproc

### ISSUE THREAD

**Issue by rgaglian** [NSO-developer/tme-demo#9]
Problem:
/home/nso/nso/support/ned-make-package-meta-data: line 42: xsltproc: command not found

Solution: 
$ sudo apt-get install xsltproc

Problem
make[3]: npm: Command not found

Solution
$ sudo apt-get install npm

**Comment by maddn** [comment]
The latest version has the option to create a docker image which includes these dependencies.

If you are building the packages locally, then you would need to manually install the dependencies. I've added some comments to the Makefile to explain this.
